[package]
name = "egui_wgpu_native"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.31.0"
egui-wgpu = { version = "0.31.0", features = ["winit"] }
egui-winit = "0.31.0"
pollster = "0.4.0"
wgpu = "24.0.1"
winit = "0.30.9"
